name: Challenges Build Test
on:
    pull_request:
        branches:
            - master
    workflow_dispatch:
jobs:
    build:
        name: 'Build Challenge Container'
        defaults:
            run:
                shell: bash
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Docker
              uses: crazy-max/ghaction-setup-docker@v3