name: Challenges Build Test
on:
    pull_request:
        branches:
            - master
    workflow_dispatch:
jobs:
    build:
        name: 'Build Challenge Container'
        defaults:
            run:
                shell: bash
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}

            - name: Print Incoming Branch
              run: echo " branch is \:\ ${{ github.head_ref }}"

            - name: List Files under Cloned Repository
              run : ls -la

            - name: Docker Compose Challenge Deployment
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                compose-file: ${{ github.head_ref }}/docker-compose.yml
                up-flags: "--build"